---
# tasks file for roles/role1
    - name: update the system
      apt:
        update_cache: yes

    - name : create jenkins directory 
      ansible.builtin.file:
        path: /home/ubuntu/jenkins_home
        state: directory
        mode: "0755"

    - name: Install Java
      apt: 
        name: openjdk-17-jdk
        state: present


    # install docker
    - name: install dependencies
      apt:
        name: "{{ docker_deps }}"
        state: present

    - name: add docker key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker repo
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: install docker
      ansible.builtin.apt:
        name: "{{ docker_engine }}"
        state: present

    - name: enable and start docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: add ubuntu user to group docker
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes
        